### PR TITLE
Cleanup "New text" page

### PR DESCRIPTION
**Pull request by link2xt**
Already fixed bootstrap layout to avoid wrapping the whole form into single `div`.

Going to remove colons and periods from input labels, move help text to `<p class="help-block">` and make sure help text consists of complete sentences.

### CODE REVIEW

**Comment by melmothx** [comment]
I took a look at the work so far. I'm a bit concerned because it basically appears as a rewriting.

This commit is especially nasty: db879890

I've had prefer whitespace-only commits on their own (and marked as such), now probably it's too late.

**Comment by link2xt** [comment]
You can install `meld` and use
```
git difftool -d -r origin/master
```

Configure `meld` to ignore  leading whitespace.

**Comment by melmothx** [comment]
Regardless of the available diffing tools, I'm sure that you'll agree with me that a clean diff is valuable for various reasons. So, what's done is done, but for the future, if you need to reindent, please do that in a separate commit and say so in the commit message. Thanks

**Comment by melmothx** [comment]
@link2xt Is this branch still a WIP as the title suggests?

**Comment by link2xt** [comment]
@melmothx I have removed [WIP]. I planned to change more, but it can be done in a separate PR later. The changes already made here are self-contained and can be reviewed as is.

**Comment by melmothx** [comment]
@link2xt looks good to me. Thanks!

I'm going to remove the js validation and the date picker, preferring the HTML5 attributes instead. No point in loading that js just for a minor thing

**Pull request merged**
