### PR TITLE
Add Kurmanji (Northern Kurdish) to known languages

### PR DESCRIPTION
**Pull request by rojenzaman**
Kurmanji (kmr): https://iso639-3.sil.org/code/kmr

### CODE REVIEW

**Comment by rojenzaman** [comment]
I created a .po file because I guessed that a Kurdish translation might come in the future. If you think that the kmr.po file will create an unnecessary load (58KB), we can only settle with `lib/AmuseWikiFarm/Utils/Amuse.pm`.

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> I created a .po file because I guessed that a Kurdish translation
> might come in the future. If you think that the kmr.po file will
> create an unnecessary load (58KB), we can only settle with
> `lib/AmuseWikiFarm/Utils/Amuse.pm`.

That load by today's standards is nothing, so no concern here. However,
the PO file by itself doesn't cut it. I can't find mention of that
language here:

http://mirrors.ctan.org/macros/latex/required/babel/base/babel.pdf

Can you take a look and let me know if I missed it somehow?

TeXlive apparently needs this package:

https://ctan.org/pkg/babel-kurmanji

Now, is this language going to be actually used or we're still in the
hypothetical land?

-- 
Marco

**Comment by rojenzaman** [comment]
> Now, is this language going to be actually used or we're still in the
> hypothetical land?

No, just a rumor. But can we still define Kurmanji at `lib/AmuseWikiFarm/Utils/Amuse.pm`?

But I don't understand why TeXlive needs babel-kurmanji.. Isn't it enough to test Kurmanji texts in the current environment? (The letters in Kurmanji are available in the Turkish and French alphabets.)

> http://mirrors.ctan.org/macros/latex/required/babel/base/babel.pdf

They did not give Kurmanji as a language code, but only gave an example from the Kurdish language:

```
Even with a certain calendar there may be variants. In Kurmanji the default variant prints
something like 30. Çileya Pêşîn 2019, but with variant=izafa it prints 31’ê Çileya Pêşînê
```

also here:

```
Basque " ' ~
Breton : ; ? !
Catalan " ' `
Czech " -
Esperanto ^
Estonian " ~
French (all varieties) : ; ? !
Galician " . ' ~ < >
Greek ~
Hungarian `
Kurmanji ^
Latin " ^ =
Slovak " ^ ' -
Spanish " . < > ' ~
Turkish : ! =
```

**Comment by melmothx** [comment]
Interesting enough, the support is already there.

https://github.com/melmothx/text-amuse/blob/master/lib/Text/Amuse/Utils.pm#L208

**Comment by melmothx** [comment]
The support on the TeX side is needed, in a way or another, otherwise the PDF output would be crappy.

**Pull request merged**
