### PR TITLE
Add Vagrantfile with a development environment

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Comment by link2xt** [comment]
@melmothx Now I am cloning amusewiki from `/vagrant` to `/home/vagrant` before running. Running it directly from `/vagrant` seems to be a better way, because you edit the code and see the result immediately. It doesn't work though, because it is impossible to create unix socket `/vagrant/var/amw.sock` on virtualbox filesystem.

Maybe it is a good idea to move `var` to `$HOME/var` everywhere?

**Comment by link2xt** [comment]
I have updated PR to create socket in `/home/vagrant/amw.sock`. Now `vagrant up` starts server at `localhost:8080` that you can modify in runtime from the host system.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> @melmothx Now I am cloning amusewiki from /vagrant to /home/vagrant before running. Running it
> directly from /vagrant seems to be a better way, because you edit the code and see the result
> immediately. It doesn't work though, because it is impossible to create unix socket
> /vagrant/var/amw.sock on virtualbox filesystem.
>
> Maybe it is a good idea to move var to $HOME/var everywhere?

Unfortunately my knowledge of vagrant is a nice zero, so feel free to
take the needed decisions and let me know if I can help on my side.

-- 
Marco

**Comment by link2xt** [comment]
@melmothx See my previous message, I think I have fixed the things, PR is ready to be merged.

> Unfortunately my knowledge of vagrant is a nice zero

Vagrant is easy to use, that is the point. I learned about it myself yesterday, actually.

You need to install VirtualBox and vagrant packages. Then `cd` to the cloned git repo of Amusewiki (branch with `Vagrantfile` of course) and run `vagrant up`. It will create a Debian-based virtual machine with Amusewiki and start it, forwarding port 80 to 8080 and port 20 to 2222.

Then you can use `vagrant ssh` to SSH into the VM and, for example, reset `amusewiki` password. With your browser you go to `localhost:8080` and see Amusewiki running. Repository itself is mounted into `/vagrant` inside the VM, so any modifications to the code immediately affect running web application.

When done, you can `vagrant halt` the VM or `vagrant destroy` it to start from scratch.

I think it makes sense to write some sort of `HACKING.md` or "Setting up development environment" guide for `amusewiki-site` aside the installation guide, so new developers can start hacking on amusewiki quickly.

**Comment by link2xt** [comment]
Hmm, now it has problems with /static files. Let's postpone it until I can confirm that it works reliably.

**Comment by link2xt** [comment]
@melmothx I have restored previous `Vagrantfile` and rebased. It works reliably, but the directory is not shared.

**Comment by melmothx** [comment]
Ok, I guess if you're not in an hurry to have this merged, I'd let it sleep a couple of days. Please take your time and let me know when is done.

**Comment by link2xt** [comment]
@melmothx I have fixed it. The problem was with nginx running as `www-data` and not having access to `/vagrant` sometimes, depending on umask settings on the host. Now nginx starts as `vagrant` user.

**Comment by melmothx** [comment]
@link2xt merged, thanks. If you have time/will, would you mind writing a doc with the workflow for this?

**Comment by link2xt** [comment]
@melmothx I think I will write a separate post for amusewiki-site that can be linked from the README next to the installation guide

**Pull request merged**
