### PR TITLE
Switch development environment to Carton

### PR DESCRIPTION
**Pull request by link2xt**
It is an attempt to address #253 and test Carton in Vagrant.

Tests do not pass yet.

### CODE REVIEW

**Comment by link2xt** [comment]
`carton exec prove -l` results:
```
Test Summary Report
-------------------
t/automatic-teaser.t            (Wstat: 512 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 124 tests but ran 1.
t/batch-upload.t                (Wstat: 512 Tests: 9 Failed: 1)
  Failed test:  9
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 61 tests but ran 9.
t/cleanups.t                    (Wstat: 1024 Tests: 47 Failed: 4)
  Failed tests:  36, 38, 40, 42
  Non-zero exit status: 4
t/controller_OPDS.t             (Wstat: 256 Tests: 301 Failed: 1)
  Failed test:  301
  Non-zero exit status: 1
t/controller_Uploads.t          (Wstat: 4096 Tests: 34 Failed: 16)
  Failed tests:  5-11, 19, 26-32, 34
  Non-zero exit status: 16
  Parse errors: Bad plan.  You planned 56 tests but ran 34.
t/editing.t                     (Wstat: 2048 Tests: 108 Failed: 8)
  Failed tests:  62-63, 66-67, 72-73, 76, 88
  Non-zero exit status: 8
  Parse errors: Bad plan.  You planned 122 tests but ran 108.
t/embed-pdf.t                   (Wstat: 51968 Tests: 286 Failed: 203)
  Failed tests:  67-131, 133-260, 277-286
  Non-zero exit status: 203
t/full-blog-mode.t              (Wstat: 2816 Tests: 228 Failed: 11)
  Failed tests:  3, 5, 9-10, 12-13, 215, 218, 221, 224, 227
  Non-zero exit status: 11
t/imager.t                      (Wstat: 6400 Tests: 53 Failed: 44)
  Failed tests:  1-8, 18-53
  Non-zero exit status: 25
  Parse errors: Bad plan.  You planned 55 tests but ran 53.
t/mail.t                        (Wstat: 512 Tests: 71 Failed: 2)
  Failed tests:  59, 71
  Non-zero exit status: 2
t/open-graph.t                  (Wstat: 512 Tests: 8 Failed: 2)
  Failed tests:  1, 8
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/preview-deferred.t            (Wstat: 65280 Tests: 325 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 346 tests but ran 325.
t/revisions-deletion.t          (Wstat: 3328 Tests: 34 Failed: 13)
  Failed tests:  2-5, 9, 14-17, 26-29
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 48 tests but ran 34.
t/revisions-files.t             (Wstat: 512 Tests: 14 Failed: 5)
  Failed tests:  6-9, 14
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 122 tests but ran 14.
t/simple-gallery.t              (Wstat: 512 Tests: 30 Failed: 13)
  Failed tests:  7, 10-17, 25, 27, 29-30
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 312 tests but ran 30.
```

**Comment by link2xt** [comment]
After `vagrant up`, `carton exec prove -l t/00-prepare-tests.t` and `carton exec prove -l t/open-graph.t` I get this error:

```
t/open-graph.t .. Corrupted file provided [_1]t/files/shot.png  at t/open-graph.t line 35.
```

**Comment by link2xt** [comment]
Probably Imager is built without the PNG format support.

**Comment by link2xt** [comment]
Updated results:
```
Test Summary Report
-------------------
t/cleanups.t                    (Wstat: 1024 Tests: 47 Failed: 4)
  Failed tests:  36, 38, 40, 42
  Non-zero exit status: 4
t/xapian.t                      (Wstat: 1024 Tests: 43 Failed: 4)
  Failed tests:  26-29
  Non-zero exit status: 4
```

**Comment by melmothx** [comment]
Two notes: you probably add libjpeg-dev and libpng-dev (or whatever they're called these days) to the vagrant machine. Imager needs to build against system libraries.

Second: `prove` swallows the output, so it's not helpful for diagnostics. Use carton exec perl -I lib t/test.t (or equivalent)

**Comment by racke** [comment]
`prove` with the `-v`flag will show diagnostics though.

**Comment by melmothx** [comment]
Re: Imager, the check was already in place at startup time: https://github.com/melmothx/amusewiki/blob/master/init-all.sh#L34

**Comment by melmothx** [comment]
@link2xt 

Trying a `vagrant up`:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/debian-9.5' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => /home/melmoth/amw/vagrant/amusewiki
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: amusewiki-run (shell)...
    default: Running: inline script
==> default: /tmp/vagrant-shell: line 4: carton: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

Was I supposed to destroy the vm?

**Comment by racke** [comment]
It certainly helps to start from a fresh state.

**Comment by melmothx** [comment]
> It certainly helps to start from a fresh state.

Yeah, doing that

**Comment by melmothx** [comment]
> > Re: Imager, the check was already in place at startup time: https://github.com/melmothx/amusewiki/blob/master/init-all.sh#L34
> 
> I do not run `init-all.sh` in Vagrantfile, because special location of the fcgi socket is required and `init-all.sh` uses the default. There is also `t/imager.t`.

Then better move the check in the fcgi script, so it's clear something is off. I'll do that in master

**Comment by melmothx** [comment]
@link2xt Or, better, in the install script. While you're working on this, can you take care of it?

**Comment by link2xt** [comment]
After rebase, I get this failure:
```
#   Failed test 'no new jobs'
#   at t/git-pulling-async.t line 125.
```

> I'm wondering if it relates to the locale, as the boxes should match, shouldn't they?

The Xapian test failures are probably related to me setting locale to `en_GB`, which is not installed in the VM. Environment variables are forwarded through `vagrant ssh` into the VM. It does not reproduce with default `en_US.UTF-8` settings.

We can ignore it, though I wonder why should application behavior depend on user locale at all.

> Then better move the check in the fcgi script, so it's clear something is off.
> ...
> Or, better, in the install script. While you're working on this, can you take care of it?

So far I have not changed `install.sh` in this branch. I install everything manually from `Vagrantfile`, mainly because `install.sh` still uses `cpanm`.

I am going to add carton option to installation script as the next step.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> After rebase, I get this failure:
> ```
> #   Failed test 'no new jobs'
> #   at t/git-pulling-async.t line 125.
> ```

Not sure where it comes from. Mine pass. Can you reproduce it at will or
is a temporary (read: timestap related) failure to clock hiccups?

>> I'm wondering if it relates to the locale, as the boxes should match, shouldn't they?
>
> The Xapian test failures are probably related to me setting locale to
> `en_GB`, which is not installed in the VM. Environment variables are
> forwarded through `vagrant ssh` into the VM. It does not reproduce
> with default `en_US.UTF-8` settings.
>
> We can ignore it, though I wonder why should application behavior
> depend on user locale at all.

Well, no, I'd like to get to the bottom of it. Do you get the warning
about the locale not installed when you log in? What the warning says?

Can you show/send me the logs of what you tried? Can you also try with a
russian (or something non-latin locale), and C locale as well? Including
the `locale` output?

My blind guess is that Xapian somewhere uses locales data to do some
parsing, something like that.

FWIW, I can't reproduct it (yet).

> So far I have not changed `install.sh` in this branch. I install
> everything manually from `Vagrantfile`, mainly because `install.sh`
> still uses `cpanm`.
>
> I am going to add carton option to installation script as the next step.

Ok, good, thanks

--
Marco

**Comment by melmothx** [comment]
@link2xt Not sure here if something is needed from me or it's simply still in progress.

**Comment by link2xt** [comment]
> Not sure here if something is needed from me or it's simply still in progress.

At this point `Vagrantfile` installs and runs Amusewiki with Carton without Debian Perl packages.

I have removed `script/install.sh` call from provisioning script because it still uses cpanm. I do everything it does manually in `Vagrantfile`.

Need to decide whether Carton becomes the default manual installation method. I am in favor of deprecating non-carton manual installation method, because maintaining lists of Perl dependencies for various operating systems is hard and it is unlikely that lists such as https://github.com/melmothx/amusewiki-site/blob/e6efc73030bd4779edecc90146b1e6d3fc3d9a18/i/il/install.muse#L190-L257 were tested recently.

If you agree to completely switch manual installation to Carton, I can also change `script/install.sh` to check that `carton` is installed and use it instead of `cpanm`. Then we will have only two installation methods: official Debian packages and Carton.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> At this point `Vagrantfile` installs and runs Amusewiki with Carton
> without Debian Perl packages.
>
> I have removed `script/install.sh` call from provisioning script
> because it still uses cpanm. I do everything it does manually in
> `Vagrantfile`.
>
> Need to decide whether Carton becomes the default manual installation
> method. I am in favor of deprecating non-carton manual installation
> method, because maintaining lists of Perl dependencies for various
> operating systems is hard and it is unlikely that lists such as
> https://github.com/melmothx/amusewiki-site/blob/e6efc73030bd4779edecc90146b1e6d3fc3d9a18/i/il/install.muse#L190-L257
> were tested recently.
>
> If you agree to completely switch manual installation to Carton, I can
> also change `script/install.sh` to check that `carton` is installed
> and use it instead of `cpanm`. Then we will have only two installation
> methods: official Debian packages and Carton.

Ok, I think there are two separate issues here. The first is the
local::lib vs. system-wide dependency approach. Manual install prefers
the first and requires you to add the lib initialization to the shell.
Once you do the eval `perl -Mlocal::lib` thing, you're fine.

The second is the dependency management. Carton is per-application, not
per user. So it must run every command with carton exec or exporting the
lib location. The rationale behind it is that developer works with a set
of dependencies and the production must match to avoid bad surprises, so
the environment is the same.

To provide the manual installation, carton could be good (and faster,
IIRC, as it skips the tests). However, this in turn requires the
documentation to be revised, as the `perl -Mlocal::lib` doesn't applies
any more.

Also see the script/generate-systemd-unit-files script and
https://amusewiki.org/library/install for CentOS. There I found more
convenient to install a fresh perl, tweak the PATH and be done with
that. Involved scripts will need adjustment as well.

My point is that cpanm vs. carton is not the real issue. If you export
PERL5LIB to ./local, cpanm will work the same (but just picks the higher
module version).

Someone should be in charge to update the snapshot file from time to
time, to avoid carrying over obsolete modules.

My main concern is how to provide init files and unit files which work
correctly and consistently under different OS.

An effort in this direction would be very welcome, so if you want to
ditch cpanm and embrace carton, I'm fine with that, as long as it works
and there's an improvement comparing with the existing situation (which
could be better but I don't think it's very bad).

Am I making sense?

--
Marco

**Comment by link2xt** [comment]
>  My point is that cpanm vs. carton is not the real issue. If you export PERL5LIB to ./local, cpanm will work the same (but just picks the higher module version).

Avoiding picking the higher version is the main reason for using carton. Otherwise the application may work differently depending on the time of installation, or break completely if some module becomes incompatible and dependency specifications are not strict enough to avoid update.

> Someone should be in charge to update the snapshot file from time to time, to avoid carrying over obsolete modules. 

Updating snapshot is a part of release procedure. Something like 1. update snapshot 2. run tests 3. build packages 4. tag release.

> An effort in this direction would be very welcome, so if you want to ditch cpanm and embrace carton, I'm fine with that, as long as it works and there's an improvement comparing with the existing situation (which could be better but I don't think it's very bad).

As for me, the main improvement is that it will be possible to make releases that don't change simply because some module maintainer released a new version. That is especially important for container images, because otherwise they are not reproducible.

Ok, I will start adding commits that use carton in installation scripts, point systemd unit files to `local/` libraries etc. then

**Comment by link2xt** [comment]
There is also a problem with `libmodule-install-perl`, which is still installed from the repo.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

>>  My point is that cpanm vs. carton is not the real issue. If you
>>  export PERL5LIB to ./local, cpanm will work the same (but just picks
>>  the higher module version).
>
> Avoiding picking the higher version is the main reason for using
> carton. Otherwise the application may work differently depending on
> the time of installation, or break completely if some module becomes
> incompatible and dependency specifications are not strict enough to
> avoid update.

This is of course reasonable but a module becoming incompatible needs to
be addressed upstream. Pinning the version can work temporarily.

>> Someone should be in charge to update the snapshot file from time to
>> time, to avoid carrying over obsolete modules.
>
> Updating snapshot is a part of release procedure. Something like 1.
> update snapshot 2. run tests 3. build packages 4. tag release.

Ok, good.

>> An effort in this direction would be very welcome, so if you want to
>> ditch cpanm and embrace carton, I'm fine with that, as long as it
>> works and there's an improvement comparing with the existing
>> situation (which could be better but I don't think it's very bad).
>
> As for me, the main improvement is that it will be possible to make
> releases that don't change simply because some module maintainer
> released a new version. That is especially important for container
> images, because otherwise they are not reproducible.

That's fair enough.

> Ok, I will start adding commits that use carton in installation
> scripts, point systemd unit files to `local/` libraries etc. then

Very good. Please let me know if you need assistance.

--
Marco

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> There is also a problem with libmodule-install-perl, which is still
> installed from the repo.

Well, could you please elaborate?

--
Marco

**Comment by link2xt** [comment]
@melmothx 
>> There is also a problem with `libmodule-install-perl`, which is still installed from the repo.

> Well, could you please elaborate?

See https://github.com/melmothx/amusewiki/pull/265/files#diff-23b6f443c01ea2efcb4f36eedfea9089R94

If I remove this line, `carton install --deployment` fails to install many packages.

**Comment by link2xt** [comment]
I probably need to add it to `cpanfile` as `build_requires` or something like this.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> I probably need to add it to cpanfile as build_requires or something like this.

Ok, please let me know if you get stuck.

-- 
Marco

**Comment by link2xt** [comment]
I have addad
```
build_requires 'Module::Install';
```
to the beginning of cpanfile. Then I `vagrant ssh`, `cd /vagrant` and do `carton install`. After running it two times, it succeeds, but looks like there are still problems with the order of install.

Not sure how to make `Module::Install` install before everything else.

**Comment by link2xt** [comment]
Here is a description of the error I get: https://perlmaven.com/cant-locate-inc-module-install-in-inc

Installing `Module::Install` before running `carton install` helps, but it is OS-dependent. Adding `configure_requires 'Module::Install';` to `cpanfile` does not help: I have to run `carton install` two times then.

**Comment by link2xt** [comment]
Here is an example of the error:
```
Searching Test::WWW::Mechanize::Catalyst (0) on cpanmetadb ...
--> Working on Test::WWW::Mechanize::Catalyst
Fetching http://cpan.metacpan.org/authors/id/J/JJ/JJNAPIORK/Test-WWW-Mechanize-Catalyst-0.60.tar.gz
-> OK
Unpacking Test-WWW-Mechanize-Catalyst-0.60.tar.gz
Copying Test-WWW-Mechanize-Catalyst-0.60.tar.gz to /vagrant/local/cache/authors/id/J/JJ/JJNAPIORK/Test-WWW-Mechanize-Catalyst-0.60.tar.gz
Entering Test-WWW-Mechanize-Catalyst-0.60
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.59 ... Yes (7.10_02)
Configuring Test-WWW-Mechanize-Catalyst-0.60
Running Makefile.PL
Can't locate inc/Module/Install.pm in @INC (you may need to install the inc::Module::Install module) (@INC contains: /vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi /vagrant/local/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at Makefile.PL line 2.
BEGIN failed--compilation aborted at Makefile.PL line 2.
-> N/A
-> FAIL Configure failed for Test-WWW-Mechanize-Catalyst-0.60. See /home/vagrant/.cpanm/work/1550431655.3221/build.log for details.
```

**Comment by melmothx** [comment]
Question: in this context, what's exactly the purpose of
Module::Install? because you're not going to install anything, or build
anything. You are just going to run it in-tree. So if the cpanfile has
all the dependencies listed, running perl Makefile.PL is useless (unless
proved otherwise).

--
Marco

**Comment by link2xt** [comment]
Here I found someone else has the same problems: https://github.com/perl-carton/carton/issues/227#issuecomment-387163259

Apparently it is Debian-patched perl which removed `.` from `@INC` for some (security?) reasons.

**Comment by melmothx** [comment]
@link2xt `.` was removed from `@INC` lately. It's possible that some modules are behind that.

**Comment by melmothx** [comment]
https://rt.cpan.org/Public/Bug/Display.html?id=121864

**Comment by melmothx** [comment]
(and upstream pinged)

**Comment by link2xt** [comment]
Some more documentation on the problem: https://wiki.gentoo.org/wiki/Project:Perl/Dot-In-INC-Removal

**Comment by link2xt** [comment]
@melmothx 
There are other packages with the same problem. I am going to collect the list of them to make sure bugs are filed for all of them and they are eventually fixed upstream. Then, need to choose some workaround, because waiting for all upstream packages to be fixed does not sound good.

**Comment by link2xt** [comment]
Here is the list of packages failing to find `inc::Module::Install` in `@INC`:
- Plack-Middleware-ReverseProxy-0.15
- Catalyst-Model-Adaptor-0.10
- DBIx-Class-Schema-Config-0.001011
- Catalyst-Plugin-ConfigLoader-0.34
- Daemon-Control-0.001008
- Catalyst-Plugin-Authorization-Roles-0.09
- Catalyst-Plugin-Session-State-Cookie-0.17
- Catalyst-Action-RenderView-0.16
- Catalyst-Plugin-Session-0.41
- Catalyst-Authentication-Store-DBIx-Class-0.1506
- Catalyst-Plugin-Authentication-0.10023
- Catalyst-View-JSON-0.36
- Test-WWW-Mechanize-Catalyst-0.60

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> Here is the list of packages failing to find `inc::Module::Install` in `@INC`:
> - Plack-Middleware-ReverseProxy-0.15
> - Catalyst-Model-Adaptor-0.10
> - DBIx-Class-Schema-Config-0.001011
> - Catalyst-Plugin-ConfigLoader-0.34
> - Daemon-Control-0.001008
> - Catalyst-Plugin-Authorization-Roles-0.09
> - Catalyst-Plugin-Session-State-Cookie-0.17
> - Catalyst-Action-RenderView-0.16
> - Catalyst-Plugin-Session-0.41
> - Catalyst-Authentication-Store-DBIx-Class-0.1506
> - Catalyst-Plugin-Authentication-0.10023
> - Catalyst-View-JSON-0.36
> - Test-WWW-Mechanize-Catalyst-0.60

It looks like re-releasing is going to fix it (at least that what folks
said on #catalyst). Which could take a while, of course. In the
meanwhile, feel free to use whatever workaround you deem necessary.

Thanks

--
Marco

**Comment by link2xt** [comment]
Ok, the `PERL_USE_UNSAFE_INC=1` workaround is in place, now to update `script/install.sh`.

**Comment by link2xt** [comment]
What is left is to get run control scripts into shape.

Debian packages have their own units (`debian/*.service`) that don't use `script/*`.

For manual installs, we have:
- `./init-all.sh` A script to run `jobber.pl` and `init-fcgi.pl` with rc script interface. Still uses `cpanm` and has a comment about `carton`.
- `script/init-fcgi.pl` Used only by `init-all.sh` and `Vagrantfile`. Should probably be removed and replaced with `plackup`, similarly to how systemd units run the application.
- `script/amusewikifarm_fastcgi.pl` Used only by `script/init-fcgi.pl`, seems to be generated by Catalyst. Now that we have Plack can be removed, too.
- `generate-systemd-unit-files` Should be updated run `plackup` via `carton exec`.

So, the plan is to remove `script/init-fcgi.pl` and `script/amusewikifarm_fastcgi.pl` and update `init-all.sh` (for rc init) and `generate-systemd-unit-files` (for systemd) to `carton`. Is it ok?

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> What is left is to get run control scripts into shape.
>
> Debian packages have their own units (`debian/*.service`) that don't use `script/*`.
>
> For manual installs, we have:
> - `./init-all.sh` A script to run `jobber.pl` and `init-fcgi.pl` with rc script interface. Still uses `cpanm` and has a comment about `carton`.
> - `script/init-fcgi.pl` Used only by `init-all.sh` and `Vagrantfile`. Should probably be removed and replaced with `plackup`, similarly to how systemd units run the application.
> - `script/amusewikifarm_fastcgi.pl` Used only by `script/init-fcgi.pl`, seems to be generated by Catalyst. Now that we have Plack can be removed, too.
> - `generate-systemd-unit-files` Should be updated run `plackup` via `carton exec`.
>
> So, the plan is to remove `script/init-fcgi.pl` and `script/amusewikifarm_fastcgi.pl` and update `init-all.sh` (for rc init) and `generate-systemd-unit-files` (for systemd) to `carton`. Is it ok?

Yeah, sure, go ahead. Also what's the plan for systems like freebsd
without systemd? Should it rely on the init-all.sh?

--
Marco

**Comment by link2xt** [comment]
> Also what's the plan for systems like freebsd without systemd? Should it rely on the init-all.sh?

I think so, `init-all.sh` is an rc script with all the common start/stop commands.

**Comment by melmothx** [comment]
@link2xt Could you check if https://metacpan.org/pod/Test::WWW::Mechanize::Catalyst installs fine now?

**Comment by dracos** [comment]
cpanm 1.7043 added the automatic setting of `PERL_USE_UNSAFE_INC` to prevent issues with that in installation as you found. Unfortunately, Debian stretch includes cpanm 1.7042...

**Comment by link2xt** [comment]
I have already set `PERL_USE_UNSAFE_INC=1` for carton. This setting is going into `script/install.sh`, so end users are not going to notice anything.

**Comment by link2xt** [comment]
I have updated `scripts/generate-systemd-unit-files` and made `Vagrantfile` install and start systemd units instead of starting services manually.

I don't start `cgit` service (`psgi/amusewiki-cgit.psgi`) because nginx also manages cgit on port 9015. Why cgit on port 9015 is both in `psgi/amusewiki-cgit.psgi` and in `sites-enabled/amusewiki`? It is also the case for Debian packages I think. Shouldn't there be only one way to start `cgit` (I prefer psgi as it does not depend on the web server)?

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> I have updated `scripts/generate-systemd-unit-files` and made
> `Vagrantfile` install and start systemd units instead of starting
> services manually.

Yeah, that's good.

> I don't start `cgit` service (`psgi/amusewiki-cgit.psgi`) because
> nginx also manages cgit on port 9015. Why cgit on port 9015 is both in
> `psgi/amusewiki-cgit.psgi` and in `sites-enabled/amusewiki`? It is
> also the case for Debian packages I think. Shouldn't there be only one
> way to start `cgit` (I prefer psgi as it does not depend on the web
> server)?

I prefer psgi too, of course, BUT see this issue:
https://github.com/melmothx/amusewiki/issues/245

This issue is a cycle. *If* you run cgit with the same user as
amusewiki, there is no reason at all to use the service and could be
embedded in the application. See
f0ad5ef26dc1392afa4c16b0991587fa7dd20ae9

So we do want privilege separation to avoid spreading the attack surface
without a good reason, and at the same time without bothering the user
with an additional setup.

On debian it is all automated, so the unit file makes sense and works
well. For manual install, I don't know really. I've been running in
cycles on this. I think already once I did some work, then realized
there was no improvement whatsoever and reverted to the fcgi_wrapper
thingy.

Maybe a Daemon::Control file would make sense, wrapping plackup wrapping
cgit, so it could be provided to manual install as init script. But they
need to be run as root (or installed separately) and wasn't really happy
with that.

Open to suggestions


--
Marco

**Comment by link2xt** [comment]
Well, I think this PR is ready at this point. Both systemd install and init-all.sh manual install methods work (I have switched to systemd only in the last commit).

For now let's keep running cgit via fcgi_wrapper, simpler setup can be moved to separate issue.

I am going to start preparing a PR for `install.muse` now to replace `local::lib` references with carton and update FreeBSD section.

**Comment by melmothx** [comment]
Excellent, thanks!

**Pull request merged**
