### PR TITLE
Move requirements to cpanfile

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Comment by link2xt** [comment]
See also: https://weblog.bulknews.net/what-is-cpanfile-and-why-do-i-want-to-use-it-9ca5b0c9529e

**Comment by melmothx** [comment]
@link2xt I see this is going to be a tormented patch. How is the debian build coping with that?

Module::Install::CPANfile seems to be a circular dependency right now.

**Comment by melmothx** [comment]
On the other hand, I'm seeing people going away from Module::Install (which was prepared by the catalyst bootstrapping). Probably it would be worth to use ExtUtils::MakeMaker::CPANfile (which is also available on debian) instead of Module::Install, but it's a whole job.

Module::Install::CPANfile is not on debian, neither, so to build it properly a debian package is needed. Not a big deal, but not fun either. Thoughts?

**Comment by link2xt** [comment]
@melmothx 
`Module::Install` is not maintained indeed, even its own documentation recommends `Dist::Zilla` now, and `ExtUtils::MakeMaker` seems to be de facto standard.

I thought about getting rid of `Makefile.PL` completely. Even though the comment at the top of `Makefile.PL` says otherwise, Catalyst needs any of `Makefile.PL`, `Build.PL`, `dist.ini`, or `cpanfile` and there is a [metacpan-api](https://github.com/metacpan/metacpan-api) project built with Catalyst and without `Makefile.PL`. Amusewiki is an application, not a module, so it only needs the `cpanfile`.

As I understand it, you need `Makefile.PL` for `dh_auto_install`, so it can install `script/amusewiki-*`. I will try to rewrite `Makefile.PL` to `ExtUtils::MakeMaker::CPANfile` then.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> @melmothx

> Module::Install is not maintained indeed, even its own documentation
> recommends Dist::Zilla now, and ExtUtils::MakeMaker seems to be de
> facto standard.

Dist:Zilla is a dependency hell and looks over-engineered to me.

> I thought about getting rid of Makefile.PL completely. Even though the
> comment at the top of Makefile.PL says otherwise, Catalyst needs any
> of Makefile.PL, Build.PL, dist.ini, or cpanfile and there is a
> metacpan-api project built with Catalyst and without Makefile.PL.
> Amusewiki is an application, not a module, so it only needs the
> cpanfile.

> As I understand it, you need Makefile.PL for dh_auto_install, so it
> can install script/amusewiki-*. I will try to rewrite Makefile.PL to
> ExtUtils::MakeMaker::CPANfile then.

Yes indeed, it's needed to install modules and files and build the
debian package via make install DESTDIR....

Ok, good luck then!

--
Marco

**Comment by link2xt** [comment]
Closed in favor of #257

**Pull request closed without merging**
