### PR TITLE
Switch from Module::Install to ExtUtils::MakeMaker::CPANfile

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Comment by link2xt** [comment]
Not ready yet, `make test` fails.

**Comment by melmothx** [comment]
@link2xt If this seems impractical, I'm not too scared to maintain an additional dependency list in the cpanfile along with the debian/control and the Module::Install Makefile.PL.

**Comment by melmothx** [comment]
@link2xt from a quick look, I don't see how the files which needs installation as well are handled. (/usr/share/perl5/AmuseWikiFarm/{root,psgi,mkits,....)

**Comment by melmothx** [comment]
https://metacpan.org/pod/File::ShareDir::Install This should help libfile-sharedir-install-perl - module for installing read-only data files

**Comment by link2xt** [comment]
Here is what is installed by `Module::Install::Catalyst` in `blib/lib/AmuseWikiFarm`:

`amusewikifarm.conf  Archive  CONTRIBUTING.md  Controller  dbicdh  I18N  Log  log4perl.conf  Middleware  mkits  Model  MYMETA.json  MYMETA.yml  psgi  README.mdwn  Role  root  Schema  Schema.pm  sql  Utils  Vagrantfile  View`

PR #258 some of them which I think should not be installed.

**Comment by melmothx** [comment]
@link2xt The test failure is mostly caused by the failure of installing shared files. You're still working on this I think or did you give up?

**Comment by link2xt** [comment]
Tests require "make install" to run now, need to use https://metacpan.org/pod/Test::File::ShareDir
There is `libtest-file-sharedir-perl` package in Debian.

**Comment by link2xt** [comment]
Catalyst has a very rigid application structure and does not allow moving the 'root/' directory. As a result, `File::ShareDir::Install` does not work.

Found a simpler solution, closing this one.

**Pull request closed without merging**
