### PR TITLE
Update i18n for tr

### PR DESCRIPTION
**Pull request by rojenzaman**
I fixed and updated some sentences, but poedit(3.0.1) fixed some of the newlines, is that acceptable?

### CODE REVIEW

**Comment by melmothx** [comment]
Well, if you have an amusewiki instance, you could try if those messages
are still picked up (I'm not so sure).

I don't know why the editor should change the msg IDs though. It
generates unwanted and unneeded noise in the git history.

Please let me know if you're in the position to try out.

Thanks

**Comment by rojenzaman** [comment]
I will try it now

I can also undo the update and continue editing in nano.

**Comment by rojenzaman** [comment]
I've [tried](https://playwithamuse.rojenz.de), there is no conflict. But still I can edit updates with nano for preventing the unneeded git noises.

**Comment by melmothx** [comment]
It looks like it's fine, although the `script/upgrade_i18n` will revert that

**Comment by melmothx** [comment]
Bottom line: we're good, thanks!

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> I fixed and updated some sentences, but poedit(3.0.1) fixed some of
> the newlines, is that acceptable? You can view, comment on, or merge
> this pull request online at:

Well, if you have an amusewiki instance, you could try if those messages
are still picked up (I'm not so sure).

I don't know why the editor should change the msg IDs though. It
generates unwanted and unneeded noise in the git history.

Please let me know if you're in the position to try out.

Thanks

-- 
Marco

**Comment by rojenzaman** [comment]
I'm translating through Poeditor, I haven't had this problem for a long time.

**Comment by melmothx** [comment]
I have no idea why this comment, which I left months ago, popped out now....

**Comment by rojenzaman** [comment]
My comments are not visible either, I think I deleted them

**Pull request merged**
